version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/themes/bytegazette

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
    volumes:
      - wpdb:/var/lib/mysql

  packer:
    image: zealbyte/packer
    volumes:
      - .:/app
    user: ${UID}:${GID}
    command: 'npm run watch'

volumes:

  wordpress:

  wpdb:
